---
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: collectiveaccess, ip: 192.168.2.145, memory: '1024', sharedfolder: ~/workspace/collective_access, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant
    servername: collectiveaccess.local
mysql:
    install: '1'
    root_password: root
    database: ca
    user: collective
    password: access
    dump: ''
php:
    install: '1'
    ppa: php
    packages: [php5.6, php5.6-cli, php5.6-intl, php5.6-mcrypt, php5.6-mysql, php5.6-curl, php5.6-gd]
xdebug:
    install: '1'
composer:
    install: '1'

